version: '3.5'
services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: docker
      MONGO_INITDB_ROOT_PASSWORD: docker

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis

volumes:
  postgres:
  mongodb:
  redis:
