version: '3.5'
services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker

volumes:
  postgres:
